CREATE TABLE IF NOT EXISTS purchase_order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_tracking_id BIGINT NOT NULL REFERENCES purchase_tracking(purchase_check_id) ON DELETE CASCADE,
  item_type TEXT NOT NULL,
  quantity INTEGER DEFAULT 1,
  part_description TEXT NOT NULL,
  company TEXT,
  is_received BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);